apiVersion: v2
type: application
name: kube-secrets-init
version: 0.9.3
appVersion: 0.4.4
kubeVersion: ">=1.16.0-0"
description: kube-secrets-init is a Kubernetes mutating admission webhook, that mutates any Pod that is using specially prefixed environment variables, directly or from Kubernetes as Secret or ConfigMap.
home: https://github.com/doitintl/kube-secrets-init
sources:
  - https://github.com/doitintl/kube-secrets-init
maintainers:
  - name: sagikazarmark
    email: mark.sagikazar@gmail.com
    url: https://sagikazarmark.hu
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update kube-secrets-init to 0.4.4
  artifacthub.io/images: |
    - name: kube-secrets-init
      image: ghcr.io/doitintl/kube-secrets-init:0.4.4
    - name: secrets-init
      image: ghcr.io/doitintl/secrets-init:latest
